### PR TITLE
Add a Dockerfile

### PR DESCRIPTION
**Pull request by ljdursi**
I'm having to make a docker image for an SGA somatic-variant-filter pipeline, so as part of that have made an SGA docker file; feel free to incorporate this into the sga repository if useful.

Note that in this docker image I have _not_ included pysam or ruffus - or even python; this is just for running the SGA executable.  We could also put together a dockerized version of the entire SGA workflow, but that would likely have a different interface; maybe something like that could go in sga-extra?

### CODE REVIEW

**Comment by jts** [comment]
Cool. I think that its fine to not include ruffus/pysam as that workflow is a bit dated. I could see there being demand for running preqc through docker so it might be worth including python/matplotlib at some point.

**Comment by ljdursi** [comment]
Good point, I'll do that right now and test it with what's in examples

**Comment by ljdursi** [comment]
Ok, done, with explanation in dockerfile comments. I note that make install doesn't put sga-preqc-report.py in ${prefix}/bin, is that intentional?

**Comment by jts** [comment]
No, that's an omission

**Comment by jts** [comment]
Thanks for the update, will merge

**Comment by mr-c** [comment]
FYI: Once Ubuntu syncs the [Debian package of SGA](https://packages.debian.org/sid/sga) to [Ubuntu Xenial](http://packages.ubuntu.com/xenial/sga), one could [request a backport](https://wiki.ubuntu.com/UbuntuBackports#Requesting_a_Backport) to your favorite [Ubuntu release](https://wiki.ubuntu.com/TrustyTahr).

Then you can skip compiling SGA and instead `apt-get install sga` it.

**Comment by jts** [comment]
Good to know, thanks.

**Pull request merged**
